config/routes.rb
Rails.application.routes.draw do


  # as the landing page only renders the predefined partials, simply give its controller a dummy #home action and thus the view, not even #index, #show...etc.
  root 'pages#home' 
  

  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  # Collections, #index, #show
  # the desired path: /collections/:name
  resources :collections, param: :collection_name, only: [:index, :show]
 
  
  # Products 
  #show certain product only
  get 'collections/:collection_name/products/:product_name', to: 'products#show'

  
    
      # get '/backpack'
      # get '/shoulder_bag'
      # get '/handbag'
      # get '/purse'
      # get '/gift_under_100'
      
    
      # get '/influencer_collection'
      # get '/graffiti_collection'
    
  # Line_items
  resources :line_items, only: [:create, :update, :destroy]
  

  # Account utility, or just use devise?
  # resources :account do
  #   get :login
  #   get :register
  # end  

  # Static pages
  # resources :pages do
  #   get :about_us
  #   get :graffiti_world
  #   get :faqs # use Vue here
  #   get :delivery_region
  #   get :contact_us
  #   get :return
  #   get :privacy_policy
  #   get :terms_of_use
  #   get :dealer_list
  # end

  # Blog pages, essentially static (or generated with editor?)
  # TODO: blog editor?
  # resources :blogs do
  #   get :lookbook
  #   get :news
  # end

  # Checkout process
  get 'carts', to: 'carts#index'
  post 'carts', to: 'line_items#update_quantity'

  resources :contact_infos

  resources :orders do
    member do
      post :paypal
    end
  end

  get "/orders/order_complete.html.erb", to: 'orders#order_complete'
  get "order_check", to: 'orders#order_check'

  put 'orders/', to: 'orders#update'

  
  

  
  
  

# TODO: Admin functionality
  # resources :admin

end

app/models/contact_info.rb
class ContactInfo < ApplicationRecord
    validates :email, :first_name, :last_name, :address, :city, :country,  :post_code, :phone, presence: true

    belongs_to :cart
    belongs_to :order
end

app/controllers/contact_infos_controller.rb
class ContactInfosController < ApplicationController
    

    def new  
        @contact_info = ContactInfo.new

        @line_items = LineItem.where(cart_id: @cart.id)
    end

    def  create
        
        
        @contact_info = @cart.add_contact_info(contact_params)
        

        if ContactInfo.exists?(cart_id: @cart.id)
            redirect_to new_order_path
        else
            redirect_back(fallback_location: {action: "new"})
            flash[:alert] ="Please check your info"
        end

        

        
    end

    private

    def contact_params
        params.require(:contact_info).permit(:email, :first_name, :last_name, :address, :building_optional, :city, :country, :province, :post_code, :phone, :cart_id, :order_id)
    end
    
    
end

app/helpers/contact_info_helper.rb
module ContactInfoHelper
end

app/views/contact_infos/_footer_terms_policies.html.erb

    <div class="row fixed-bottom">
        <div id="refund" class="col-xs-4">Refund Policy</div>
        <div id="privacy" class="col-xs-4">Privacy Policy</div>
        <div id="terms-of-service" class="col-xs-4">Terms of Service</div>
    
    
    
    </div>


app/views/contact_infos/_item_info.html.erb

<% line_items.each do |line_item|%>
    <div id="item-list" class="row">
        <div id="image" class="col-xs-3">
            <!--FIXME: put the actual image after the function is finished-->
            <%= image_tag Product.find(line_item.id).image, style: "width: 100px" %></p>
        </div>

        <div id="item_name" class="col-xs-5">
            <%= Product.find_by(id: line_item.product_id).product_name %>
        </div>

        <div id="total" class="col-xs-4">
            <%= line_item.total %>
        </div>
    
            <!-- FIXME: Why the f**king line_items content appear again after everything's done???-->
    

    </div>
<% end %>


    <hr>

    <div id="coupon" class="row">
        <input type="text" placeholder="Gift cart or discount code">
        <button type="submit">Apply</button>

    </div>

    <hr>

    <div id="subtotal_fee" class="row">
        <span>Subtotal</span>
        <!-- FIXME: refactor this to helper?-->
        <span class="pull-right">USD$<%= LineItem.where(cart_id: cart.id).sum(:total) %></span>
        <!-- TODO: implement shipping-->
        <br>
        <span>Shipping</span>
            <% if request.original_url.include?  "contact_infos"  %>
                <span class="pull-right">Calculated at next step</span>
            <% else %>
                <span class="pull-right">USD$<%= @shipping%></span>
            <% end%>
    </div>

    <hr>

    <div id="total" class="row">
        <span>Total</span>

        <% if request.original_url.include?  "contact_infos" %>
                <span class="pull-right">USD $<%= LineItem.where(cart_id: cart.id).sum(:total) %></span>
            <% else %>
                <span class="pull-right">USD $<%= LineItem.where(cart_id: cart.id).sum(:total) +@shipping %></span>
            <% end%>

        
    </div>



app/views/contact_infos/new.html.erb
<!-- A more "formal" way for "contact" and "shipping_payment" should be writing #new and render info inside of them.
But as I want to update all of the data on screen, let's just separate it into two different pages;
btw it's more convenient for path designation.
-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    
</head>
<body>
    
    <div id="page" class="container">
        <div class="row">
            <div class="col-xs-8" id="info">
                <div id="brand-logo" class="row text-center"><%= image_tag 'JumpFromPaper_Logo-01_250x.png' %></div>
                <!-- TODO: checkout process nav -->

 

                <%= form_for @contact_info  do |f| %>
                    <!-- FIXME: hardcoded field sizes for now, need to modify to dynamically changing -->
                    

                    <div id="contact" class="row">
                    
                    <!-- FIXME: 
                    <span class="">Already have an account? <a href="#">Log in</a></span>
                    
                    <br>
                    <br>
                    restore it if account functionality is implemented -->
                    
                    <!-- invisible tag to hold default value -->
                    
                    
                    
                    

                     
                    <span>Contact information</span>
                    
                    <p><%= f.text_field :email ,placeholder: "Email", size: 65 %></p>
                    
                    </div>

                    
                    

                    <div id="address" class="row">
                    <span>Shipping address</span>
                    <br>
                    <%= f.text_field :first_name , placeholder: "First name", size: 30 %>
                    <%= f.text_field :last_name,  placeholder: "Last name", size: 30 %>
                    <%= f.text_field :address, placeholder: "Address", size: 65 %>
                    <%= f.text_field :building_optional, placeholder: "Apartment, suite, etc. (optional) ", size: 65 %>
                    <%= f.text_field :city, placeholder: "City", size: 65 %>
                    <br>
                    
                    <%= f.country_select :country, prompt: "Please select country", size: 25 %>
                    <br>
                    <%= f.text_field :province, placeholder: "Province", size: 17%>
                    <%= f.text_field :post_code, placeholder: "Postcode", size: 17 %>
                    <%= f.text_field :phone, placeholder: "Phone", size: 65%>
                    <%= f.hidden_field :cart_id, value: @cart.id %>
                    <%= f.hidden_field :order_id, value: 1 %> 
                    <!-- Give it a dummy ID to show it's not finished yet.
                    Later we can still locate it with cart id.
                    It will be updated when the order is really created.-->

                    <br>
                    <button id="return" class="btn"><%= link_to "< Return to cart", carts_path(@line_items) %></button>
                    
                    
                    
                    
                    <button id="submit" class="pull-right"><%= f.submit "Continue to shipping method" %></button>

                    
                    </div>

                    
                    

                  
                <% end %>


            
            
            
            
            </div>
            <div id="item-info" class="col-xs-4">
            <%= render 'item_info', { line_items: @line_items, cart: @cart } %>
            </div>
        
        
        
        
        
        </div>

        
    
    
    
    
    
    </div>
    </div>
</div>




</body>

<footer>
    
</footer>
</html>