config/routes.rb
Rails.application.routes.draw do


  # as the landing page only renders the predefined partials, simply give its controller a dummy #home action and thus the view, not even #index, #show...etc.
  root 'pages#home' 
  

  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  # Collections, #index, #show
  # the desired path: /collections/:name
  resources :collections, param: :collection_name, only: [:index, :show]
 
  
  # Products 
  #show certain product only
  get 'collections/:collection_name/products/:product_name', to: 'products#show'

  
    
      # get '/backpack'
      # get '/shoulder_bag'
      # get '/handbag'
      # get '/purse'
      # get '/gift_under_100'
      
    
      # get '/influencer_collection'
      # get '/graffiti_collection'
    
  # Line_items
  resources :line_items, only: [:create, :update, :destroy]
  

  # Account utility, or just use devise?
  # resources :account do
  #   get :login
  #   get :register
  # end  

  # Static pages
  # resources :pages do
  #   get :about_us
  #   get :graffiti_world
  #   get :faqs # use Vue here
  #   get :delivery_region
  #   get :contact_us
  #   get :return
  #   get :privacy_policy
  #   get :terms_of_use
  #   get :dealer_list
  # end

  # Blog pages, essentially static (or generated with editor?)
  # TODO: blog editor?
  # resources :blogs do
  #   get :lookbook
  #   get :news
  # end

  # Checkout process
  get 'carts', to: 'carts#index'
  post 'carts', to: 'line_items#update_quantity'

  resources :contact_infos

  resources :orders do
    member do
      post :paypal
    end
  end

  get "/orders/order_complete.html.erb", to: 'orders#order_complete'
  get "order_check", to: 'orders#order_check'

  put 'orders/', to: 'orders#update'

  
  

  
  
  

# TODO: Admin functionality
  # resources :admin

end

app/models/order.rb
class Order < ApplicationRecord
    # belongs_to :cart
    # belongs_to :user
    has_many :line_items
    has_one :contact_info

    
    
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  
  def  new
    @line_items = LineItem.where(cart_id: @cart.id)

    @contact_info = ContactInfo.find_by(cart_id: @cart.id)

    # FIXME: deliver the value to view first, need to attach it into DB
    @shipping = 30.00

    @order = Order.new
  end
  

  def create
    order_items = LineItem.where(cart_id: @cart.id)
    contact_info = ContactInfo.find_by(cart_id: @cart.id)
        
    total = order_items.sum(:total)
    shipping_fee = 30
    comments = comment_param[:comments]
    process = "Payment pending"

        

    #TODO: correct it as the devise account functionaity is finished
    account = contact_info.email

    

    @order = Order
            .new(total: total, 
                 shipping_fee: shipping_fee,
                 comments: comments,
                 process: process,
                 account: account
                 )
            
    @order.save

    # Update the order_id from dummy one to real one
    order_items.update_all(order_id: @order.id)
    
    

                      
    # At the same time, remember to clear the cart
    
    session[:cart_id] = nil

    

    redirect_to "/orders/order_complete.html.erb"
  end

  def order_complete
    render 'order_complete'
  end

  def order_check
    
  end

  def index
    

    @orders = Order.where("account = ?", params[:account])

    @line_items = LineItem.where("order_id = ?", !@orders.empty? ? @orders.first.id : nil)
  end

  def update
    order_id = params[:order_id]
    condition = params[:process]
    order = Order.find(order_id)


    if condition == "Order cancelled"
      order.update(process: condition)
      flash[:notice] = "Order cancelled."
    elsif condition == "Return processing"
      order.update(process: condition, return: 'Y')
      flash[:notice] = "Return processing."
    else
    end

    redirect_back(fallback_location: 'order_check')
    
  end


  private

    def comment_param
      params.require(:order).permit(:comments)
    end

    

    

    
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
    def cancel_or_return(id)
        # TODO: correct the logic later. Using "Payment pending" or not as condition for now.
        

        if !@orders.empty? && @orders.find(id).process == "Payment pending"
            
            link_to 'Cancel Order', {controller: "orders", action: "update", order_id: id, process: "Order cancelled"}, method: :put, data: { confirm: "Are you sure to cancel?\n The order will still be kept in record." }
        elsif
            link_to 'Return & Refund', '#'
        else
            return
        end
    end
end

app/views/orders/_footer_terms_policies.html.erb
<div class="container">
    <div class="row">
        <div id="refund" class="col-xs-4">Refund Policy</div>
        <div id="privacy" class="col-xs-4">Privacy Policy</div>
        <div id="terms-of-service" class="col-xs-4">Terms of Service</div>
    
    
    
    </div>

</div>

app/views/orders/index.html.erb
<div class="container text-center">
<h1>Orders for <%=params[:account]%></h1>
</div>
<hr>


<% @orders.each do |o| %>
<table class="table table-bordered">
    <div class="container">
    <%if @orders.blank? %>
    <%= "Oops, you typed in wrong email, or the email can't be found." %>
    <%= link_to 'Try again.', controller: "orders", action: "order_check" %>
    <%end%>

    
            <div id="orderID-<%=o.id%>" class="row"><h3>Order number <%= o.created_at.strftime("%Y%M%d") %><%=o.id%></h3></div>
            <hr>
            <div id="items" class="row">
                <h4>Items</h4>
                    <%@line_items.each do |i| %>
                        <p id="each-item">
                            
                            <span><%= Product.find_by(id: i.id).product_name %>&nbsp</span>
                            
                            <span>USD$<%= Product.find_by(id: i.id).price %></span>
                            
                        </p>
                    <%end%>
                    <hr>
            </div>
            
            <div class="row">Shipping Fee: USD$<%= o.shipping_fee %></p></div>
            
            <div class="row"><p>Total: USD$<%= o.total %></p></div>
            
            <div class="row"><p>Ordered Date: <%= o.created_at.strftime("%Y%M%d") %></p></div>
            
            <div class="row"><p>Process: <%=o.process%></p></div>
            
            <div class="row"><p>Comments <%= o.comments %></p></div>

            

            

            <div id="action" class="row">
                <!-- Pass the ID into helper from invisible tag-->
                <% id = o.id %>
                <%= cancel_or_return(id) %>
                <br>
                <%= link_to 'Contact Service', 'https://www.jumpfrompaper.com/pages/contact-us' %>
            
            </div>
        
        </div>
        
        <hr>


        
        
<% end %>
    </table>


app/views/orders/new.html.erb
<!-- A more "formal" way for "contact" and "shipping_payment" should be writing #new and render info inside of them.
But as I want to update all of the data on screen, let's just separate it into two different pages;
btw it's more convenient for path designation.
-->

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div id="page" class="content container">
        


    <%= form_for @order, url: orders_path, method: :post do |f| %>
        <div class="row">
            <div class="col-md-8" id="info">

                <div id="brand-logo" class="row text-center"><%= image_tag 'JumpFromPaper_Logo-01_250x.png' %></div>
                <!-- TODO: checkout process nav -->

                <div class="row">
                    <div id="contact" class="col-xs-2">
                        <span>Contact</span>
                    </div>
                    
                    

                    <div class="col-xs-10">
                        <span><%= @contact_info.email%></span>
                    </div>
                    
                </div>
                
                <hr>
                        
                    

                <div class="row">
                    <div id="address" class="col-xs-2">
                        <span>Ship to</span>
                    </div>
                        
                    <div class="col-xs-10">
                        <span>
                        <%= "#{@contact_info.address}, #{@contact_info.building_optional},#{@contact_info.post_code},#{@contact_info.city},#{@contact_info.country}" %>
                        </span>
                    </div>
                </div>
                
                <hr>

                
                
                <div id="shipping" class="row">
                    <div id="method" class="col-xs-2">Shipping Method</div>
                        
                    <div class="col-xs-10">
                        <span>DHL Express Worldwide</span>
                        <span class="col-xs-2 pull-right">USD$<%= @shipping%></span>
                    </div>
                        
                

                </div>

                <hr>

                
                  <%= f.label :Comments%>
                  <br>
                  <%= f.text_area :comments, rows: 3, cols: 50 %>
                

                <hr>

                
                    
                <br>

                <div id="action" class="row">
                    

                    <button id="return" class="btn"><%= link_to "< Return to customer information", new_contact_info_path(@contact_info) %></button>

                    <%= f.submit "Confirm Order", class: 'pull-right'%>
                    

                    
                    
                    
                    
                
                    <!-- TODO: complete order page and pay with Paypal later (maybe use client-side implementation?)-->

                    


                    <!-- TODO: better praceice: redirect to server-side Paypal, generating order at the same time. Order is finished as the payment is done. -->
                    <!-- TODO: after the order is finished, the customer should be able to check the order by email or with account -->
                    

                    
                </div>

                


                    

                

            
            </div>
            
            <div id="item-info" class="col-md-4">
                <%= render 'contact_infos/item_info', { line_items: @line_items, cart: @cart, shipping: @shipping } %>
            </div>

             

                    
        
        
        
        
        
        </div>
    <% end %>
   
    
    
    
    
    
    </div>




</body>





</html>

app/views/orders/order_check.html.erb
<h1>Check order</h1>
<p>Please enter your email address here to show your order(s).</p>

<%= form_tag("/orders", method: "get") do %>
    <%= text_field_tag(:account) %>
    <%= submit_tag("Submit")%>
<% end %>

app/views/orders/order_complete.html.erb
<h1>Congrats!</h1>
<p>Please go to Paypal below to finish payment. 
<br>
Once the payment is confirmd, we'll send you a confirmation email. 
<br>
Or you can check order <%= link_to 'here', controller: "orders", action: "order_check" %>
<br>Let's happily anticipate!</p>

<div id="paypal-button-container"></div>



<script src="https://www.paypalobjects.com/api/checkout.js"></script>
<script>
// Render the PayPal button
paypal.Button.render({
// Set your environment
env: 'sandbox', // sandbox | production

// Specify the style of the button
style: {
  layout: 'vertical',  // horizontal | vertical
  size:   'medium',    // medium | large | responsive
  shape:  'rect',      // pill | rect
  color:  'gold'       // gold | blue | silver | white | black
},

// Specify allowed and disallowed funding sources
//
// Options:
// - paypal.FUNDING.CARD
// - paypal.FUNDING.CREDIT
// - paypal.FUNDING.ELV
funding: {
  allowed: [
    paypal.FUNDING.CARD,
    paypal.FUNDING.CREDIT
  ],
  disallowed: []
},

// Enable Pay Now checkout flow (optional)
commit: true,

// PayPal Client IDs - replace with your own
// Create a PayPal app: https://developer.paypal.com/developer/applications/create
client: {
  sandbox: 'AZDxjDScFpQtjWTOUtWKbyN_bDt4OgqaF4eYXlewfBP4-8aqX3PiV8e1GWU6liB2CUXlkA59kJXE7M6R',
  production: '<insert production client id>'
},

payment: function (data, actions) {
  return actions.payment.create({
    payment: {
      transactions: [
        {
          amount: {
            total: '0.01',
            currency: 'USD'
          }
        }
      ]
    }
  });
},

onAuthorize: function (data, actions) {
  return actions.payment.execute()
    .then(function () {
      window.alert('Payment Complete!');
    });
}
}, '#paypal-button-container');
</script>