config/routes.rb
Rails.application.routes.draw do


  # as the landing page only renders the predefined partials, simply give its controller a dummy #home action and thus the view, not even #index, #show...etc.
  root 'pages#home' 
  

  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  # Collections, #index, #show
  # the desired path: /collections/:name
  resources :collections, param: :collection_name, only: [:index, :show]
 
  
  # Products 
  #show certain product only
  get 'collections/:collection_name/products/:product_name', to: 'products#show'

  
    
      # get '/backpack'
      # get '/shoulder_bag'
      # get '/handbag'
      # get '/purse'
      # get '/gift_under_100'
      
    
      # get '/influencer_collection'
      # get '/graffiti_collection'
    
  # Line_items
  resources :line_items, only: [:create, :update, :destroy]
  

  # Account utility, or just use devise?
  # resources :account do
  #   get :login
  #   get :register
  # end  

  # Static pages
  # resources :pages do
  #   get :about_us
  #   get :graffiti_world
  #   get :faqs # use Vue here
  #   get :delivery_region
  #   get :contact_us
  #   get :return
  #   get :privacy_policy
  #   get :terms_of_use
  #   get :dealer_list
  # end

  # Blog pages, essentially static (or generated with editor?)
  # TODO: blog editor?
  # resources :blogs do
  #   get :lookbook
  #   get :news
  # end

  # Checkout process
  get 'carts', to: 'carts#index'
  post 'carts', to: 'line_items#update_quantity'

  resources :contact_infos

  resources :orders do
    member do
      post :paypal
    end
  end

  get "/orders/order_complete.html.erb", to: 'orders#order_complete'
  get "order_check", to: 'orders#order_check'

  put 'orders/', to: 'orders#update'

  
  

  
  
  

# TODO: Admin functionality
  # resources :admin

end

app/models/cart.rb
class Cart < ApplicationRecord
    # This line may trigger user validation.
    # As non-users are allowed to checkout, what about skipping this relationship?
    # belongs_to :user

    # Cart is only a container for products to put in, like a notebook has many pages. Therefore cart itself cannot well present the content inside, we need to create another model LineItem to represent this relationship.
    has_many :line_items
    
    
    has_one :contact_info

    def add_product(product, cart_id, product_id)
        current_item = line_items.find_by(product_id: product_id)

        # Add new line_item record when there's no existed one; else if a cart has a product with existed record, just add its quantity
        if !current_item
            current_item = line_items.build(
            product_id: product_id,
            cart_id: cart_id,
            order_id: 1, # set to a dummy one to pass authentication , will correct it on checkout
            price: product.price, 
            total: product.price * 1
            # It's ok to hardcode as the quantity defaults 1 when added to cart, which is just like the behaviors of Pinkoi customers (though they can adjust quantity when adding to cart... usually I would only buy one piece of each product).
            )
        else
            current_item.quantity += 1
        end
        current_item

    end

    def add_contact_info(param_info)
        # Ensure there's only one contact_info first
        new_contact = ContactInfo.find_by(cart_id: param_info[:cart_id])

        # If there's a contact_info with identical cart_id, update it, else build new
        if new_contact
            new_contact = new_contact.update(param_info)
        else
            new_contact = build_contact_info(param_info)
            new_contact.save
        end

        
        
        return new_contact

        

    end

    
    
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    

    
    
    def index

        @line_items = LineItem.where(cart_id: @cart.id)

        @contact_info = ContactInfo.new

    end

    

    

    


    

    

    


end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb



<!-- Divide the content into 3 rows-->
<div id="form" class="container">
    <!-- Row: Basic cart info like Product, Price... etc.-->
    <div id="title" class="row">
        <span class="col-xs-8">PRODUCT</span>
        <span class="col-xs-2">PRICE</span>
        <span class="col-xs-2">QUANTITY</span>
        

        <hr>
    </div>
    
    
    <div id="item-info">
    <!-- Row, may be many: Line item info-->
      <% @line_items.each do |line_item| %>
        <%= form_for :line_item, remote: true, authenticity_token: true do |f| %>

        <div id="content-<%=line_item.id %>" class="row">

            <!-- Include an invisible line_item id and let it sent in params when form submitted -->
            <%= hidden_field_tag :id, line_item.id %>
            
            
            
            <span id="product-image" class="col-xs-3">
                <!--FIXME: put the actual image after the function is finished-->
                <p><%= image_tag Product.find(line_item.id).image, style: "width: 100px" %></p>
                
            </span>

            <span id="product-name" class="col-xs-5">
                <!-- TODO: link_to product page -->
                <p><h4><%= Product.find(line_item.product_id).product_name  %></h4></p>
                
                <p>JumpFromPaper</p>
            </span>

            <span id="price" class="col-xs-2">
                <%= line_item.price  %>
            </span>
            
            
            <div id="quantity" class="col-xs-2">
                
                <!-- TODO: Add inventory to products, then apply upper limit of quantity by inventory amount -->
                <%= f.select :quantity, options_for_select(1..10, selected: line_item.quantity), {}, onchange: 'this.form.submit(); '  %>
                <!-- Explanation: as the quantity changes, the form will be submitted and posted to 'carts', ie. line_items#update_quantity. As the params is correctly filled in, the controller action will be triggered and updates DB data. -->
                
                

                <br>
                <p id="remove_button">
                    <%= link_to 'Remove', line_item_path(id: line_item.id), method: :delete,  data: {confirm: 'Are you sure?'}  %>
                </p>
            </div>
            
            
            
        </div>
        <hr>

        <% end %>
      <% end %>
    </div>

    

        <!-- Row: Fee info and checkout-->
        <div id="info" class="row">
            <span id="custom_notice">*Customs are not included in the price of goods.</span>
            <br>
            <span id="shipping-to-add">*Shipping will be calculated at checkout.</span>
            <br>
            
            
            
            <span id="subtotal" class="pull-right">
                Subtotal USD$<%= @line_items.sum(:total) %> 
            </span>
            <br>
            <!-- This is first loaded from DB, then carts.js controls the summing and updating. -->

            <span class="pull-right">
                
                <button class="btn"><%= link_to "CHECK OUT", new_contact_info_path(@contact_info) %></button>
            </span>
            
        </div>

        

            
        
        </div>
    
    


</div>



        
        <!-- FIXME: move notes div to order section
        
            -->



<!-- Failed implementation:
As Vue is pretty awesome with live data replacement, I wanted to use it to set quantity and then calculate item's total price and subtotal without refreshing page, then post all of the data to controller.
However this method is a bit hard and not so imperative for me now, since:
1. It would be hard to retrieve data from multiple same-named Vue component instances.
2. Data formats are not aligned between Rails and Vue.
3. Indeed, 2. can be overcome by using JSON for alignment. Rails serves as API and sends JSON for Vue to process, then Vue POSTs JSON to Rails controller.
This method is kind of isomorphic, not so suitable for me that wants to focus on backend for now. BTW I'm not certain how to process JSONified data, and it may not be the fastest implementation, cool though, the priority should be finishing this demo project ASAP.
-->
<!-- Proposed implementation for live data replacement:
1. Use f.select to show dropdown (defaulted 1 as it is in schema). The item total and subtotal can be calculated at this stage using defaults.
2. POST with AJAX to line_items controller and save to database immediately.
3. Write a VanillaJS to listen to quantity change and track the data on page. Then make calculation and live update.

This method may not be so smooth though, it's still better than the original JFP site which needs to "update cart" and refresh.
-->



<%= javascript_pack_tag 'carts' %>


















app/views/carts/contact_info.html.erb
<!-- A more "formal" way for "contact" and "shipping_payment" should be writing #new and render info inside of them.
But as I want to update all of the data on screen, let's just separate it into two different pages;
btw it's more convenient for path designation.
-->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    
</head>
<body>
    <div id="page" class="container">
        <div class="row">
            <div class="col-xs-8" id="info">
                <div id="brand-logo" class="row text-center"><%= image_tag 'JumpFromPaper_Logo-01_250x.png' %></div>
                <!-- TODO: checkout process nav -->

                <%= form_for @contact_info  do |f| %>
                    <!-- FIXME: hardcoded field sizes for now, need to modify to dynamically changing -->
                    <div id="contact" class="row">
                    <span>Contact information</span>
                    <span class="pull-right">Already have an account? <a href="#">Log in</a></span>
                    
                    <p><%= f.text_field :email, placeholder: "Email", size: 65 %></p>
                    
                    </div>

                    <!-- TODO: member mailing-->
                    

                    <div id="address" class="row">
                    <span>Shipping address</span>
                    <br>
                    <%= f.text_field :first_name, placeholder: "First name", size: 30 %>
                    <%= f.text_field :last_name, placeholder: "Last name", size: 30 %>
                    <%= f.text_field :address, placeholder: "Address", size: 65 %>
                    <%= f.text_field :building_optional, placeholder: "Apartment, suite, etc. (optional) ", size: 65 %>
                    <%= f.text_field :city, placeholder: "City", size: 65 %>
                    <br>
                    <!-- TODO: city-state gem-->
                    <%= f.country_select :country, prompt: "Please select country", size: 25 %>
                    <br>
                    <%= f.text_field :province, placeholder: "province", size: 17%>
                    <%= f.text_field :post_code, placeholder: "Postcode", size: 17 %>

                    <br>
                    <span id="return">< Return to cart</span>
                    <span id="submit" class="pull-right"><%= f.submit "Continue to shipping method" %></span>

                    <div class="row">
                    </div>
                    </div>

                    
                    

                  
                <% end %>


            
            
            
            
            </div>
            <div id="item-info" class="col-xs-4">
            <%= render 'item_info', { line_items: LineItem.where(cart_id:  @cart.id), cart: @cart } %>
            </div>
        
        
        
        
        
        </div>

        
    
    
    
    
    
    </div>
    </div>
</div>




</body>

<footer>
    
</footer>
</html>

app/views/carts/index.html.erb
<!-- TODO: make a new path nav here? -->






<h1 class="text-center"><b>Shopping Cart</b></h1>
<hr>

<%= render 'form' %>

<!-- Always remember to include JS at the end! If it is included before any element it refers to, the execution order causes problem -->


<!-- FIXME: Disable JS before a new version is finished

-->





app/views/carts/shipping_payment.html.erb
<!-- A more "formal" way for "contact" and "shipping_payment" should be writing #new and render info inside of them.
But as I want to update all of the data on screen, let's just separate it into two different pages;
btw it's more convenient for path designation.
-->

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <div id="page" class="content">
        <div class="row">
            <div class="col-md-8" id="info">

            <%= render 'footer_terms_policies' %>
            </div>
            <div id="item-info" class="col-md-4">
            <%= render 'item_info' %>
            </div>
        
        
        
        
        
        </div>
    
    
    
    
    
    </div>




</body>
</html>