config/routes.rb
Rails.application.routes.draw do


  # as the landing page only renders the predefined partials, simply give its controller a dummy #home action and thus the view, not even #index, #show...etc.
  root 'pages#home' 
  

  
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  # Collections, #index, #show
  # the desired path: /collections/:name
  resources :collections, param: :collection_name, only: [:index, :show]
 
  
  # Products 
  #show certain product only
  get 'collections/:collection_name/products/:product_name', to: 'products#show'

  
    
      # get '/backpack'
      # get '/shoulder_bag'
      # get '/handbag'
      # get '/purse'
      # get '/gift_under_100'
      
    
      # get '/influencer_collection'
      # get '/graffiti_collection'
    
  # Line_items
  resources :line_items, only: [:create, :update, :destroy]
  

  # Account utility, or just use devise?
  # resources :account do
  #   get :login
  #   get :register
  # end  

  # Static pages
  # resources :pages do
  #   get :about_us
  #   get :graffiti_world
  #   get :faqs # use Vue here
  #   get :delivery_region
  #   get :contact_us
  #   get :return
  #   get :privacy_policy
  #   get :terms_of_use
  #   get :dealer_list
  # end

  # Blog pages, essentially static (or generated with editor?)
  # TODO: blog editor?
  # resources :blogs do
  #   get :lookbook
  #   get :news
  # end

  # Checkout process
  get 'carts', to: 'carts#index'
  post 'carts', to: 'line_items#update_quantity'

  resources :contact_infos

  resources :orders do
    member do
      post :paypal
    end
  end

  get "/orders/order_complete.html.erb", to: 'orders#order_complete'
  get "order_check", to: 'orders#order_check'

  put 'orders/', to: 'orders#update'

  
  

  
  
  

# TODO: Admin functionality
  # resources :admin

end

app/models/product.rb
class Product < ApplicationRecord
    belongs_to :collection
    has_many :line_items
    

    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    include FindingMethods

    def show
        @product = Product.find_by(product_name: titleized_param_product)

        #TODO: conditionally hide empty collections?
    end

    private

    


    

end


# original show:
# def show
#   @product = Product.find_by(product_name: params[:product_name])
# end

# Should turn params[:product_name] back to original 
# eg. "brown-rice-spaceman-backpack" -> "Brown Rice Spaceman Backpack"

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_add_to_cart.html.erb

<!-- Post to line_items to :create a new line item-->
<div id="add-to-cart" class="">
<%= button_to 'ADD TO CART', line_items_path(product_id: @product.id) 
%>

<!-- Unlike adjusting quantity on product page like the original JFP site, quantity changing is moved to cart page like Pinkoi does -->
<!--FIXME: In first iteration, user is redirected to cart immediately after submitting as default; refactor to Ajax with buttons in later iterations to prevent default -->
<!-- TODO: change color for button after submit -->
</div>
<br>
<hr>





app/views/products/show.html.erb
<%= render 'partials/path_nav' %>

<div class="container">
    <div id="prev_next" class="text-right row">
    <hr>
    <!-- TODO: conditionally show 'previous', '|', 'next' -->
    <!--Reversed arrangement because of "pull-right". WTF? Let frontend take care of it. I'm backend. -->
        
        <span id="next" class="pull-right"><%= link_to 'Next Product →', '#' %></span>
        <span id="hyphen" class="pull-right">&nbsp;|&nbsp;</span>
        <span id="prev" class="pull-right"><%= link_to '←Previous Product', '#' %></span>
    </div>
        
</div>


<!-- FIXME: Let's just take three collection for practice, if there's need to interact with more collections, just add later-->
<div id="page-container" class="container">
    <div class="row">
        <div id="picture" class="col-xs-6 text-center">
            <%= image_tag @product.image, class: "Max-diwth 100%" %>
            <br>
        </div>

        <div id="product-info" class="col-xs-6">
            <h2><b><%= @product.product_name %></b></h2>
            <br>

            <!-- TODO: use number_to_currency method for price in i18n implementation, default USD$ -->
            <span>USD$<%= @product.price %></span><br>
            <hr>

            <%= render 'add_to_cart' %>

            <div id="product-description">
                <!-- Add .html_safe to ensure to description HTML tags can be applied instead of shown directly -->
                <h4><b><%= @product.description_short.html_safe %></b></h4>
                <br>
                <%= @product.description_long.html_safe %>
            </div>
            <br>

            <div class="size">

            <h4><b>SIZE</b></h4>

            <ul>
                <!-- TODO: write unit helper for lengths in i18n implementation, default: cm -->
                <li>Contracted: <%= @product.size_contracted %> cm</li>
                <li>Extended: <%= @product.size_extended %> cm </li>
                <% if @product.size_strap != "" %>
                <li>Strap: <%= @product.size_strap %> cm</li>
                <% end %>
                <% if @product.size_hand_drop != "" %>
                <li>Hand Drop: <%= @product.size_hand_drop %> cm</li>
                <% end %>
            </ul>

            </div>

            <div class="detail">
                <h4><b>DETAIL</b></h4>
                
                <ul>
                    <li>Style: <%= @product.detail_style %></li>
                    <li>Material: <%= @product.detail_material %></li>
                    <li>Cleaning: <%= @product.detail_cleaning %></li>
                    <li>Max capacity: <%= @product.detail_capacity %></li>
                </ul>

            </div>

            <!-- TODO: hide the next three sections with JS, shown on:click.
            The headings for now are temporary. -->
            <div class="color">
                <h4>COLOR</h4>
                <span>
                Please note that actual colors may vary due to the different monitor settings or different lighting effect in the model shoot.
                </span>
            </div>

            <div class="delivery">
                <h4>DELIVERY</h4>
                <span>
                Delivery normally will take 3-10 business days. We ship to AU ,CA ,UK ,MX ,FR ,GE ,NL ,NOR ,SKR ,JP and other places. For more detail, please click <a href="https://www.jumpfrompaper.com/pages/delivery-region">Here</a> 
                </span>
            </div>

            <div class="return_warranty">
                <h4>RETURN & WARRANTY</h4>
                <span>
                Returns are eligible within 28 days of receipt. For more detail, please click <a href="https://www.jumpfrompaper.com/pages/return">Here</a><br>
                All JumpFromPaper products are provided with six months warranty that covers defects in materials and workmanship.
                </span>
            
            </div>

            <div id="stars_social"></div>

            <!-- TODO: use Vanilla to generate form and conditionally show reviews
            <div id="reviews" class="row">
             
            <h3><b>Customer Reviews</b></h3>
            <a href="#" class="pull-right">Write a review</a>

            </div>
            -->

        </div>
    
    
    
    </div>

    <br>
    <br>
    <br>
    <br>

    <!--TODO: Randomly show products in 6 auto-adjusting columns for this stage
    <div div="recently_viewed" class="row ">
         

        <h4><b>♥ Recently Viewed Items</b></h4>
        <div id="pictures" class="justify-content-around">
            <%= image_tag 'products/dummy.png' %>
            <%= image_tag 'products/dummy.png' %>
            <%= image_tag 'products/dummy.png' %>
            <%= image_tag 'products/dummy.png' %>
            <%= image_tag 'products/dummy.png' %>
            <%= image_tag 'products/dummy.png' %>
        </div>
        
    </div>
    -->

    <!--TODO: Randomly show products in 4 auto-adjusting columns for this stage
    <div div="you_may_also_like" class="row">
        
        <h3>You May Also Like</h3>
        <div id="pictures" class="justify-content-around">
            <%= image_tag 'products/dummy.png' %>
            <%= image_tag 'products/dummy.png' %>
            <%= image_tag 'products/dummy.png' %>
            <%= image_tag 'products/dummy.png' %>
           
        </div>
        
    </div>
    -->

</div>



